### ISSUE TITLE
Add field in models for access point of archived URL

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-nomination#1]
@vphill requested a field in the Project? model (or a set of fields) that would allow us to put the base URL for an OpenWayback instance that provides access to the seeds crawled in the Nomination Tool. 
If that seed is present then we could have a link directly into the archive created for it. 
Might make the nomination tool an access system as well. 
(issue moved over from Trac)

**Comment by somexpert** [comment]
Would this link be something we'd want to be displayed in each Project's About page, if the link was present for that project?

**Comment by ldko** [comment]
yes

**Comment by ldko** [comment]
I think the plan might also be to use that base URL to construct links for urls/seeds to where they exist for playback in external OpenWayback instances. This could possibly be displayed on the `/url` views. Is that part of the plan @vphill ?

**Comment by vphill** [comment]
Yes that is also a desire.  So the nomination tool could be used as an access tool once a based openwayback access point is established for a project. @ldko can give info on the best way to construct the link into openwayback.  I think the calendar view for a given URL is the way to go.

**Comment by ldko** [comment]
For example, if the nominated url in the project is:
http://www.unt.edu
and the base url for the OpenWayback instance is:
http://webarchive.library.unt.edu/unt/fall2015/
the url we would generate to link to the archived url in OpenWayback would be:
http://webarchive.library.unt.edu/unt/fall2015/*/http://www.unt.edu

or if the nominated url is:
http://www.artlies.org
and the base url for the OpenWayback instance is:
http://webarchive.library.unt.edu/artlies/
the url we would generate to link to the archived url in OpenWayback would be:
http://webarchive.library.unt.edu/artlies/*/http://www.artlies.org

**Comment by somexpert** [comment]
gotcha. should be easy enough to do
