### ISSUE TITLE
Replace select box with Select2

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#102]
We should replace the selection box that requires holding certain button combos to select multiple values with [Select2](https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox), which makes it much easier to provide multiple selections without OS-dependent instructions. I'm pretty sure [this](https://github.com/unt-libraries/django-nomination/blob/master/nomination/templates/nomination/url_add.html#L126) is the place in the template requiring the change.

**Comment by ldko** [comment]
It may also be this template too: https://github.com/unt-libraries/django-nomination/blob/master/nomination/templates/nomination/url_listing.html unless we fix the duplication going on in these templates...

**Comment by somexpert** [comment]
ah yes, I'll it there too. Also, I've gone with a pure javascript [implementation](http://slimselectjs.com/selects) instead of Select2.

**Comment by ldko** [comment]
Do we also want to use slim select on single-select boxes @vphill @somexpert ?

**Comment by somexpert** [comment]
Was gonna say it doesn't seem _as_ useful there, but it _would_ add search functionality, and we certainly wouldn't be _losing_ anything by using it.

**Comment by somexpert** [comment]
I've gone ahead and started using slim select for all selection boxes.
