### ISSUE TITLE
search_json view displays incorrect URLs

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#18]
The view should only be showing the URLs related to the given project. There is validation on the passed project slug, raising a 404 if the slug does not match a project, and yet if it does match, all the URLs for _every_ project are returned. Just need to add a simple filter on the query to limit the returned URLs to those related to the project.

**Comment by somexpert** [comment]
_Or_ perhaps the URL itself should be changed to not include the project slug if a universal list of all submitted URLs is actually the desired behavior.

**Comment by ldko** [comment]
I think it is meant to return the URLs for that specific project only.

**Comment by somexpert** [comment]
Alright, I'll add a filter to the query found [here.](https://github.com/unt-libraries/django-nomination/blob/master/nomination/url_handler.py#L463)
