### ISSUE TITLE
Move scripts

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#19]
There are currently 3 command-line scripts (fielded_batch_ingest.py, csv_to_pickle.py, dynamic_form.py, and batch_valuesets.py) that are under nomination. These should either be removed from the project if they are no longer relevant or moved to a separate directory if they are still useful. If they are kept and moved, then instructions should be included on their usage.

**Comment by somexpert** [comment]
So dynamic_form.py isn't actually a command-line script. From a precursory lookover, it seems as though it printed the html form of all the metadata attributes that were specified for the URLs of a project. This could have been used for a view that no longer exists, or perhaps it was an early attempt to do the forms without using Django's built-in tools for dynamic forms. My recommendation would be to just delete this file. I couldn't find any trace of this in use anywhere in the app.

The other 3 scripts provide command-line batch uploading or URLs, URL attributes, and value sets. While these have some use if you have many things to add to a project, we plan on adding such functionality to the app itself. So I think these can be deleted. We can still reference them with the 0.9.0 tag if we need to once we get around to adding that functionality to the app.

**Comment by ldko** [comment]
I think dynamic_form.py was an experimentation that was never finished and if it isn't referenced anywhere in the app then we can delete it. I would prefer not to delete the other scripts until the functionality is actually added to the app unless you have another reason you want to delete them now.

**Comment by somexpert** [comment]
I have no problem with keeping the 3 scripts for now. I'll move them to a separate directory, but do you think I need to mention them in the README? The scripts themselves have decent documentation as-is, but I can mention that they exist if we think people will actually be using them before we add the functionality in the app.

**Comment by ldko** [comment]
It is fine to mention their existence.
