### ISSUE TITLE
Three unreachable branches in create_json_browse()

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#26]
[This](https://github.com/unt-libraries/django-nomination/blob/0.9.0/nomination/url_handler.py#L381-#L382) branch, [this](https://github.com/unt-libraries/django-nomination/blob/0.9.0/nomination/url_handler.py#L387-#L388) one, and [this](https://github.com/unt-libraries/django-nomination/blob/0.9.0/nomination/url_handler.py#L428) one are all unreachable. They should be removed or modified.

**Comment by ldko** [comment]
Another unused aspect of this function, I don't think the `url_attribute` parameter is used.
