### ISSUE TITLE
Add setting/s for contact info for use in the templates

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#63]
Currently we have hardcoded the contact info. Need to make it into a project setting and add the instructions for that setting in the README.

**Comment by damonkelley** [comment]
We could also leave this to template layer. App clients can override templates relatively easily. We could also take advantage of `{% include ... %}` I imagine.

**Comment by somexpert** [comment]
So you're saying have like a `contact_info.html` template? That would work. Wouldn't be hard to do, and easy enough to explain in the README.

**Comment by damonkelley** [comment]
Yeah. There are probably a couple of ways we could do it too.

I personally like this method _a little_ more than using settings. I prefer it when app settings determine how the app should behave, and leave the templates to carry out the presentation.

just my 2 cents
