### ISSUE TITLE
Inaccessible views.

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#65]
Currently, there are several views which a normal user would be completely unaware of because we have no link to them anywhere in the UI. These views include two [JSON views](https://github.com/unt-libraries/django-nomination/blob/0.9.0/nomination/urls.py#L14-#L15) and two [project feeds](https://github.com/unt-libraries/django-nomination/blob/0.9.0/nomination/urls.py#L33-#L34).

@vphill, do you want links to some or all of those placed in the navigation bars, or do you want those views deleted?

**Comment by vphill** [comment]
I think having the two feeds as little feed icons on the main project page and then probably on the about page too would be a good thing.  We should probably add them to the HTML as <link> elements as well. 

The Json views I'm not sure about.  I'm not sure what they return without digging into things.

**Comment by somexpert** [comment]
So we're going to add links to the feeds in two of the project views, and comment the JSON views so we know what they're doing.
