### ISSUE TITLE
Use get_object_or_404

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-nomination#93]
We really should be using [get_object_or_404](https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#get-object-or-404) any place that will grabbing a database record based on the URL, such as [here](https://github.com/unt-libraries/django-nomination/blob/master/nomination/views.py#L841). Would help to avoid some unnecessary server errors.

**Comment by ldko** [comment]
@madhulika95b would you see if this issue is fully resolved?
